version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ~/docker/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ~/docker/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  heartbeat:
    build:
      context: heartbeat/
    volumes:
      - ./heartbeat/config/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:rw
    networks:
      - elk
  
  metricbeat:
    build:
      context: metricbeat/ 
    volumes:
      - ./metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:rw
      - ./metricbeat/config/modules.d/:/usr/share/metricbeat/modules.d/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk      
    environment:
      - "MYSQL_ROOT_PASSWORD=changemeplease"
    depends_on:
      - elasticsearch
#      - nginx
#      - apache2

networks:

  elk:
    driver: bridge
